# Generated by Django 3.2.9 on 2024-03-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employ_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('employ_name', models.CharField(max_length=10, null=True)),
                ('employ_age', models.IntegerField(null=True)),
                ('employ_gender', models.CharField(max_length=255, null=True)),
                ('employ_Phone', models.CharField(max_length=11, null=True)),
            ],
        ),
    ]
