# Generated by Django 3.2.9 on 2024-03-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_id', models.CharField(max_length=10, null=True)),
                ('attend_name', models.CharField(max_length=10, null=True)),
                ('attend_statu', models.CharField(choices=[('已签到', 'Option 1'), ('已签退', 'Option 2')], max_length=10, null=True)),
                ('attend_stime', models.DateTimeField(null=True)),
                ('attend_etime', models.DateTimeField(null=True)),
            ],
        ),
    ]
